version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - dependabot
      - meta
    target-branch: dev
    allow:
      - dependency-name: "@vscode/test-web"
    groups:
      vscode-test-web:
        applies-to: version-updates
        update-types:
          - patch
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - dependabot
      - meta
    ignore:
      - dependency-name: "@types/vscode" # Manually bump with the VS Code engine version
      - dependency-name: "@types/json-schema"
      - dependency-name: "@types/node" # Manually bump with the VS Code engine version
    target-branch: dev
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
      prod-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      security:
        applies-to: security-updates
        dependency-type: production
      security-dev:
        applies-to: security-updates
        dependency-type: development
      