blank_issues_enabled: true
contact_links:
- name: Project Discord thread
  url: https://discord.com/channels/574720535888396288/1350968830230396938
  about: |
    Use the project thread to discuss with developers directly.

    When in doubt, always ask in the thread first.
